[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
[".config/emacs"]
    type = "archive"
    url = "https://github.com/doomemacs/doomemacs/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
{{ if .personal -}}
[".dotfiles"]
    type = "git-repo"
    url = "https://github.com/szorfein/dotfiles"
    refreshPeriod = "0"
[".ansible/collections/ansible_collections/szorfein/hardening"]
    type = "git-repo"
    url = "https://github.com/szorfein/ansible-collection-hardening"
    refreshPeriod = "0"
[".ansible/collections/ansible_collections/szorfein/privacy"]
    type = "git-repo"
    url = "https://github.com/szorfein/ansible-collection-privacy"
    refreshPeriod = "0"
[".ansible/collections/ansible_collections/szorfein/desktop"]
    type = "git-repo"
    url = "https://github.com/szorfein/ansible-collection-desktop"
    refreshPeriod = "0"
{{ else -}}
[".dotfiles"]
    type = "archive"
    url = "https://github.com/szorfein/dotfiles/archive/main.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".ansible/collections/ansible_collections/szorfein/hardening"]
    type = "archive"
    url = "https://github.com/szorfein/ansible-collection-hardening/archive/main.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".ansible/collections/ansible_collections/szorfein/privacy"]
    type = "archive"
    url = "https://github.com/szorfein/ansible-collection-privacy/archive/main.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".ansible/collections/ansible_collections/szorfein/desktop"]
    type = "archive"
    url = "https://github.com/szorfein/ansible-collection-desktop/archive/main.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
{{ end -}}
